version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WS_URL: ws://localhost:3000

    working_dir: /app
    ports:
      - "3000:3000"
    image: kurumi:latest
    env_file:
      - .env
