import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
    const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

    const [data, setData] = useState("");

    const mutate = trpc.auth.test2.useMutation();
    trpc.auth.test.useSubscription(undefined, {
        onData(d) {
            setData(d.test);
        },
    });

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
                <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
                    Create <span className="text-purple-300">T3</span> App
                </h1>
                <p className="text-2xl text-gray-700">This stack uses:</p>
                <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-3 lg:w-2/3">
                    <div>
                        <p>Data: {data}</p>
                        <input
                            className="bg-black text-white"
                            onChange={(e) => mutate.mutateAsync({ test: e.target.value })}
                        />
                    </div>
                </div>
                <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
                    {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
                </div>
            </main>
        </>
    );
};

export default Home;
