import { useToast } from "@chakra-ui/react";
import React, { ReactNode, useEffect } from "react";
import { io, Socket } from "socket.io-client";
import { useWebsocket } from "../hooks/useWebsocket";
import { ClientToServerEvents, ServerToClientEvents } from "../types/websocket.events";
import { env } from "../env/client.mjs";
// import { getSession } from "next-auth/react";

const socket: Socket<ServerToClientEvents, ClientToServerEvents> = io(env.NEXT_PUBLIC_WS_URL, {
    reconnection: true,
    reconnectionDelay: 2000,
    transports: ["websocket", "polling"],
    rememberUpgrade: true,
    autoConnect: false,
    withCredentials: true,
});

export const SocketContext = React.createContext<{
    socket: Socket<ServerToClientEvents, ClientToServerEvents>;
}>({ socket });

/**
 * Contains base logic for websocket connection
 * @returns
 */
const SocketInterface: React.FC<{ children: ReactNode }> = ({ children }) => {
    const firstDisconnect = React.useRef(true);
    const { socket, connected } = useWebsocket();
    const toast = useToast();

    useEffect(() => {
        socket.connect();

        return () => {
            socket.disconnect();
        };
    }, [socket]);

    useEffect(() => {
        // Dont show toast on first disconnect
        // This is because the socket is disconnected on first render
        // and we dont want to show a toast on first render
        // This is a hacky solution but it works
        // the above this was generated by copiolet lol
        // this only works in prod because of react strict mode
        if (firstDisconnect.current) {
            firstDisconnect.current = false;
            return;
        }
        toast({
            title: connected ? "Connected to websocket" : "Disconnected from websocket",
            status: connected ? "success" : "error",
            duration: 7000,
            isClosable: true,
        });
        firstDisconnect.current = false;
    }, [connected, toast]);

    return <>{children}</>;
};

export const SocketManager: React.FC<{ children: ReactNode }> = ({ children }) => {
    return (
        <SocketContext.Provider value={{ socket }}>
            <SocketInterface>{children}</SocketInterface>
        </SocketContext.Provider>
    );
};

export default SocketContext;
